version: '3'

services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: 'redis:latest'
    api:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        volumes: 
            - /usr/app/node_modules
            - ./server:/usr/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PG_PORT=5432
            - PG_HOST=postgres
            - PG_DATABASE=postgres
            - PG_USER=postgres
            - PG_PASSWORD=postgres_password
    client:
        stdin_open: true
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - /usr/app/node_modules
            - ./client:/usr/app
    worker:
        build:
            context: ./worker
            dockerfile: Dockerfile.dev
        volumes:
            - /usr/app/node_modules
            - ./worker:/usr/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    nginx:
        restart: always
        depends_on:
            - api
            - client
        build: 
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports: 
            - '3050:80'